### PR TITLE
Fix battery_alert.yaml issues for latest HA

### PR DESCRIPTION
**Pull request by KptnKMan**
Hi,

Small PR to fix the issues with this battery_template.yaml package.

I have tested this upto v0.117.3 and everything works fine.

I added documentation and changelog for details.

### CODE REVIEW

**Comment by idfxken** [comment]
As you could see, there's a working pr standing open since february for the deprecated goups/control/hidden. 
So might be best to just fork the repo and link it here

**Comment by KptnKMan** [comment]
I saw that, but this is code modifications that I've been using since last year, and recently decided to make a complete PR.

I already created a fork, you can see it from this PR.

**Comment by notoriousbdg** [comment]
Thanks for the PR!

**Comment by KptnKMan** [comment]
Awesome, thanks!
Thanks for making this package. :)

**Pull request merged**
